[package]
name = "checkdot-sui-coin"
version = "0.1.0"

[dependencies.Sui]
git = 'https://github.com/MystenLabs/sui.git'
rev = 'sui-v1.38.4'
subdir = 'crates/sui-framework/packages/sui-framework'

[dependencies.MoveStdlib]
git = 'https://github.com/MystenLabs/sui.git'
rev = 'sui-v1.38.4'
subdir = 'crates/sui-framework/packages/move-stdlib'

[addresses]
cdtToken = "0x0"
cdt = "0xfa800cc4e6d28d935afafe87c69a71eeb7a889cbb89d819da10efdda851f81ed"